/**
 * @Author:  jager
 * @Email:   lhj168os@gmail.com
 * @File:    sess
 * @Date:    2022/3/10 10:22 上午
 * @package: metatemp
 * @Version: v1.0.0
 *
 * @Description:
 *
 */

package metatemp

const ISessTemp = `// Code generated by metactl.
// Edit ISession interface and implement it.

package sess

type ISession interface {
	GetUid() int64
	GetGid() int64
}
`
